-- MySQL Script generated by MySQL Workbench
-- Tue Feb  6 14:09:08 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BDPets
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BDPets
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BDPets` DEFAULT CHARACTER SET utf8 ;
USE `BDPets` ;

-- -----------------------------------------------------
-- Table `BDPets`.`tbl_pets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDPets`.`tbl_pets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `especie` VARCHAR(45) NULL,
  `raca` VARCHAR(45) NULL,
  `sexo` VARCHAR(45) NULL,
  `peso` VARCHAR(45) NULL,
  `porte` VARCHAR(45) NULL,
  `nome` VARCHAR(45) NULL,
  `data_de_nasc` VARCHAR(45) NULL,
  `nome_dono` VARCHAR(45) NULL,
  `celular_dono` VARCHAR(45) NULL,
  `obs` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
